### ISSUE TITLE
Support `ghp.repo` for pull requests

### ISSUE THREAD

**Issue by cortsf** [cortsf/quterofi#1]
Declaring 

``` toml
[[github_repos]]
alias = "fzf"
user = "junegunn"
repo = "fzf"
```

Should create the following engines, at least:

``` json
{"gh.fzf": "https://github.com/search?q=repo%3Ajunegunn%2Ffzf+{}&type=issues"}
{"ghi.fzf": "https://github.com/junegunn/fzf/issues?q={}"}
{"ghp.fzf": "https://github.com/junegunn/fzf/pulls?q={}"}
```
