### ISSUE TITLE
Don't fail when there is no engine declaration for a given rule

### ISSUE THREAD

**Issue by cortsf** [cortsf/quterofi#12]
Example toml file:

``` toml
[[engine_rules]]
er_template = "search_engines"
er_alias = "{alias}"
er_url = "{url}"
```

Parsing this file will fail since there is no `[[search_engines]]`. Allow such cases in which there are no engines declarations for a given rule.
