### ISSUE TITLE
Consider allowing users to declare quickmarks with arguments and/or abbreviations

### ISSUE THREAD

**Issue by cortsf** [cortsf/quterofi#31]
Consider allowing `quterofi/open` to accept (non standard) quickmarks  with arguments (solution 1). Alternatively, allow quickmarks to be used as abbreviations, with cursor repositioning (solution 2)

# Solution 1 (arguments)

``` toml
[[quickmark_rules]]
qr_template = "github_repos"
qr_alias = "ghin.{alias}"
qr_argument_separator = "_"
qr_url = "https://github.com/{user}/{repo}/issues/{1}?irrelevant_stuff"

[[github_repos]]
alias = "qr"
user = "cortsf"
repo = "quterofi"
```

``` json
{"ghin.qr_1": "https://github.com/cortsf/quterofi/issues/1?irrelevant_stuff"}
{"ghin.qr_2": "https://github.com/cortsf/quterofi/issues/2?irrelevant_stuff"}
{"ghin.qr_n": "https://github.com/cortsf/quterofi/issues/n?irrelevant_stuff"}
```

# Solution 2 (abbreviations)
For this to work, `quterofi/open` will have to do some basic math to figure the right cursor position after formatting the url.

``` toml
[[quickmark_rules]]
qr_template = "github_repos"
qr_alias = "ghin.{alias}"
qr_cursor_position = 41
qr_url = "https://github.com/{user}/{repo}/issues/?irrelevant_stuff"

[[github_repos]]
alias = "qr"
user = "cortsf"
repo = "quterofi"
```

``` json
{"ghin.qr": "https://github.com/cortsf/quterofi/issues/__here__?irrelevant_stuff"}
```

In this example after submitting the word `ghin.qr` with a special key press, `ghin.qr` will be replaced with the corresponding url, with the cursor positioned `__here__`

Cursor position could be specified with `|`:

``` toml
[[quickmark_rules]]
qr_template = "github_repos"
qr_alias = "ghin.{alias}"
qr_url = "https://github.com/{user}/{repo}/issues/|?irrelevant_stuff"
```

**Comment by cortsf** [comment]
Closing as not needed. This problem can be solved using search engines (yes, I'm stupid)

``` toml
[[engine_rules]]
er_template = "github_repos"
er_alias ="ghin.{alias}"
er_url = "https://github.com/{user}/{repo}/issues/{}"
```

``` json
{"ghin.qr": "https://github.com/cortsf/quterofi/issues/{}"}
```
