### ISSUE TITLE
Allow user to declare engines using some sort of templates

### ISSUE THREAD

**Issue by cortsf** [cortsf/quterofi#4]
Quterofi currently supports only two kind of engine declarations, with `[[engines]]` and `[[github_repos]]`:

``` toml
[[engines]]
alias = "gl"
url = "https://www.google.com/search?q={}"

[[github_repos]]
alias = "fzf"
user = "junegunn"
repo = "fzf"
```

Allow users to declare rules or templates instructing quterofi how to read engines from engines.toml, instead of providing a function to parse only two particular cases. If possible, make these rules explicit (and mandatory) in a self-contained engines.toml.

The above engines.toml could be rewritten with something like:
``` toml
## Rules
####################

[[engine_rules]]
template = "engines"
alias = "{alias}"
url = "{url}"

[[engine_rules]]
template = "github_repos"
alias = "gh.{alias}"
url = "https://github.com/search?q=repo%3A{user}%2F{repo}+{}&type=issues"

[[engine_rules]]
template = "github_repos"
alias ="ghi.{alias}"
url = "https://github.com/{user}/{repo}/issues?q={}"

[[quickmarks_rules]]
template = "github_repos"
alias ="gh.{alias}"
url = "https://github.com/{user}/{repo}"

## Engines
####################

[[engines]]
alias = "gl"
url = "https://www.google.com/search?q={}"

[[github_repos]]
alias = "fzf"
user = "junegunn"
repo = "fzf"
```
