### ISSUE TITLE
Consider merging engines and quickmarks

### ISSUE THREAD

**Issue by cortsf** [cortsf/quterofi#44]
Allow these merged engines/quteromarks rules to be declared with or without the empty `{}` replacement braces, such that

Using this rule would generate the equivalent of a search engine, because it makes use of the empty pair of curly braces:

``` toml
[[quterofi_rules]]
qr_template = "github_repos"
qr_alias = "gh.{alias}" 
qr_url = "https://github.com/search?q=repo%3A{user}%2F{repo}+{}&type=issues"

```

Using this rule would generate the equivalent of a quickmark/quteromark, since there is no empty pair of curly brances on the url
```toml
[[quterofi_rules]]
qr_template = "github_repos"
qr_alias = "gh.{alias}" 
qr_url = "https://github.com/{user}/{repo}"
```

Also consider extending engines to allow any arbitrary number of arguments using placeholders with numbered indexes (`{0}`, `{1}`, etc)

```toml
[[quterofi_rules]]
qr_template = "some_template_name"
qr_alias = "some.{alias}" 
qr_url = "https://www.something.com/making_use_of_{1}_and_also_of_{0}_and_of_{1}_again"
```
